package com.xiaogang.myapp.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig liulanSmartDaoConfig;

    private final LiulanSmartDao liulanSmartDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        liulanSmartDaoConfig = daoConfigMap.get(LiulanSmartDao.class).clone();
        liulanSmartDaoConfig.initIdentityScope(type);

        liulanSmartDao = new LiulanSmartDao(liulanSmartDaoConfig, this);

        registerDao(LiulanSmart.class, liulanSmartDao);
    }
    
    public void clear() {
        liulanSmartDaoConfig.getIdentityScope().clear();
    }

    public LiulanSmartDao getLiulanSmartDao() {
        return liulanSmartDao;
    }

}
