package com.xiaogang.myapp.db;

import de.greenrobot.dao.DaoException;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LIULAN_SMART.
 */
public class LiulanSmart {

    /** Not-null value. */
    private String goods_id;
    /** Not-null value. */
    private String emp_id;
    /** Not-null value. */
    private String goods_name;
    /** Not-null value. */
    private String goods_cover;
    /** Not-null value. */
    private String sell_price;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient LiulanSmartDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LiulanSmart() {
    }

    public LiulanSmart(String goods_id) {
        this.goods_id = goods_id;
    }

    public LiulanSmart(String goods_id, String emp_id, String goods_name, String goods_cover, String sell_price) {
        this.goods_id = goods_id;
        this.emp_id = emp_id;
        this.goods_name = goods_name;
        this.goods_cover = goods_cover;
        this.sell_price = sell_price;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLiulanSmartDao() : null;
    }

    /** Not-null value. */
    public String getGoods_id() {
        return goods_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoods_id(String goods_id) {
        this.goods_id = goods_id;
    }

    /** Not-null value. */
    public String getEmp_id() {
        return emp_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmp_id(String emp_id) {
        this.emp_id = emp_id;
    }

    /** Not-null value. */
    public String getGoods_name() {
        return goods_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    /** Not-null value. */
    public String getGoods_cover() {
        return goods_cover;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoods_cover(String goods_cover) {
        this.goods_cover = goods_cover;
    }

    /** Not-null value. */
    public String getSell_price() {
        return sell_price;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSell_price(String sell_price) {
        this.sell_price = sell_price;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
